version: "3.3"

services:
  db:
    image: postgres:latest
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ./.env

  backend:
    build: .
    restart: always
    ports:
      - '8000:8000'
    env_file:
      - "./.env"
    depends_on:
      - db
